import { ArrowRight, BadgeCheck, Map, ShieldCheck, Star, Waves } from 'lucide-react';
import { Link } from '../app/router';
import { ListingGrid } from '../components/listings/ListingGrid';
import { SearchBar } from '../components/search/SearchBar';
import { useMarketplace } from '../context/MarketplaceContext';
import { destinationCards } from '../data/marketplaceData';

export function HomePage() {
  const { allListings, updateFilters } = useMarketplace();
  return <><section className="market-hero"><div className="market-hero__image" /><div className="shell market-hero__content"><p className="eyebrow">Stay beautifully across the Philippines</p><h1>Find a place that feels like part of the journey.</h1><p>Island villas, mountain cabins, and city homes—curated for the way Filipinos travel.</p><SearchBar elevated /></div><div className="market-hero__trust shell"><span><BadgeCheck />Verified hosts</span><span><ShieldCheck />Secure booking</span><span><Star />Guest-loved stays</span></div></section><section className="home-section shell"><header className="section-title"><div><p className="eyebrow">Explore by destination</p><h2>Where will you go next?</h2></div><Link to="/explore">View all places <ArrowRight /></Link></header><div className="destination-grid">{destinationCards.map((destination) => <Link to="/explore" key={destination.province} onClick={() => updateFilters({ province: destination.province, locality: '', query: '' })}><img src={destination.image} alt={`${destination.province} destination`} /><div><h3>{destination.province}</h3><p>{destination.caption}</p><span>Explore stays <ArrowRight /></span></div></Link>)}</div></section><section className="home-section home-featured"><div className="shell"><header className="section-title"><div><p className="eyebrow">Popular right now</p><h2>Stays guests keep loving</h2></div><Link to="/explore">See every stay <ArrowRight /></Link></header><ListingGrid listings={allListings.slice(0, 8)} /></div></section><section className="home-section shell local-promise"><div className="local-promise__visual"><img src="https://images.unsplash.com/photo-1540202404-a2f29016b523?auto=format&fit=crop&w=1400&q=88" alt="Tropical Philippine island escape" /><div><Map /><strong>10 provinces</strong><span>and growing</span></div></div><div><p className="eyebrow">Made for local discovery</p><h2>From quick weekend trips to dream island escapes.</h2><p>Search by province, city, or municipality. Compare homes on the map, save favorites, and keep every confirmed trip in one place.</p><ul><li><Waves />Beachfront and island stays</li><li><Map />Interactive location-first search</li><li><ShieldCheck />Clear pricing in Philippine pesos</li></ul><Link className="primary-button" to="/explore">Start exploring <ArrowRight /></Link></div></section><section className="host-cta"><div className="shell"><div><p className="eyebrow">Have a place guests would love?</p><h2>Turn your space into someone’s favorite Philippine memory.</h2></div><Link className="light-button" to="/host">Become a host <ArrowRight /></Link></div></section></>;
}
