import { BadgeCheck, CheckCircle2, Home, ShieldCheck, TrendingUp } from 'lucide-react';
import { useState } from 'react';
import { navigate } from '../app/router';
import { useMarketplace } from '../context/MarketplaceContext';
import { amenities, categories, locationHierarchy } from '../data/marketplaceData';

const provinceCoordinates = { Palawan: [11.2,119.4], Cebu: [10.3,123.9], Bohol: [9.7,124], Aklan: [11.7,122.4], 'Surigao del Norte': [9.8,126.1], Batangas: [13.8,121], Laguna: [14.2,121.3], Benguet: [16.4,120.6], 'Ilocos Norte': [18.2,120.6], 'Metro Manila': [14.58,121] };

export function HostPage() {
  const { createHostListing } = useMarketplace(); const [submitted, setSubmitted] = useState(null); const [province, setProvince] = useState('Palawan');
  const localities = locationHierarchy.find((item) => item.province === province)?.localities || [];
  const submit = (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const [lat,lng] = provinceCoordinates[province]; const listing = createHostListing({ title: data.get('title'), province, region: locationHierarchy.find((item) => item.province === province)?.region, locality: data.get('locality'), localityType: data.get('locality').includes('City') ? 'City' : 'Municipality', category: data.get('category'), price: Number(data.get('price')), guests: Number(data.get('guests')), bedrooms: Number(data.get('bedrooms')), beds: Number(data.get('beds')), baths: Number(data.get('baths')), lat: lat + Math.random() * .04, lng: lng + Math.random() * .04, image: data.get('image') || 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=88', description: data.get('description'), amenities: amenities.slice(0,4) }); setSubmitted(listing); };
  if (submitted) return <section className="host-success shell"><CheckCircle2 /><p className="eyebrow">Listing created</p><h1>Your place is ready for preview.</h1><p>This demo listing is saved on your device and now appears in search.</p><button className="primary-button" onClick={() => navigate(`/stays/${submitted.slug}`)}>View your listing</button></section>;
  return <><section className="host-hero"><div className="shell"><div><p className="eyebrow">Host on Lakbay</p><h1>Share your place. Welcome the Philippines.</h1><p>Create a polished listing and start reaching local travelers in minutes.</p></div><div className="host-stats"><span><strong>₱18k</strong><small>illustrative monthly opportunity</small></span><span><strong>3 steps</strong><small>to publish your demo listing</small></span></div></div></section><section className="host-workspace shell"><div className="host-benefits"><article><Home /><div><h3>You’re in control</h3><p>Choose your price, availability, and house rules.</p></div></article><article><ShieldCheck /><div><h3>Built-in protection</h3><p>Production launch can add identity and payment verification.</p></div></article><article><TrendingUp /><div><h3>Reach local travelers</h3><p>Appear in province, locality, category, and map searches.</p></div></article><article><BadgeCheck /><div><h3>Quality-first presentation</h3><p>Showcase your space with clear details and guest-ready amenities.</p></div></article></div><form className="host-form" onSubmit={submit}><header><p className="eyebrow">Create a demo listing</p><h2>Tell us about your place</h2></header><label>Listing title<input name="title" required placeholder="e.g. Quiet beach villa in El Nido" /></label><div className="two-fields"><label>Province<select value={province} onChange={(event) => setProvince(event.target.value)}>{locationHierarchy.map((item) => <option key={item.province}>{item.province}</option>)}</select></label><label>City / Municipality<select name="locality" required>{localities.map((item) => <option key={item}>{item}</option>)}</select></label></div><div className="two-fields"><label>Category<select name="category">{categories.filter((item) => item.id !== 'all').map((item) => <option value={item.id} key={item.id}>{item.label}</option>)}</select></label><label>Price per night<input name="price" required type="number" min="500" step="100" placeholder="4500" /></label></div><div className="four-fields">{[['guests','Guests'],['bedrooms','Bedrooms'],['beds','Beds'],['baths','Baths']].map(([name,label]) => <label key={name}>{label}<input name={name} required type="number" min="1" defaultValue="2" /></label>)}</div><label>Cover image URL <span>Optional</span><input name="image" type="url" placeholder="https://images.example.com/your-place.jpg" /></label><label>Description<textarea name="description" required rows="5" placeholder="What makes your stay special?" /></label><button className="primary-button" type="submit">Create listing</button><small>Demo listings remain only in this browser. Production publishing requires secure account verification and a database.</small></form></section></>;
}
