import { Bath, BedDouble, Heart, MapPin, Share2, Star, UsersRound, Wifi, Wind, Waves } from 'lucide-react';
import { Link } from '../app/router';
import { BookingCard } from '../components/booking/BookingCard';
import { ListingGrid } from '../components/listings/ListingGrid';
import { MarketplaceMap } from '../components/map/MarketplaceMap';
import { useMarketplace } from '../context/MarketplaceContext';

const amenityIcons = { 'Wi-Fi': Wifi, 'Air conditioning': Wind, 'Beach access': Waves };

export function ListingPage({ slug }) {
  const { allListings, favorites, toggleFavorite } = useMarketplace();
  const listing = allListings.find((item) => item.slug === slug);
  if (!listing) return <section className="simple-empty shell"><h1>Stay not found</h1><Link className="primary-button" to="/explore">Explore all stays</Link></section>;
  const saved = favorites.includes(listing.id); const gallery = listing.gallery?.length ? listing.gallery : [listing.image, listing.image, listing.image];
  const nearby = allListings.filter((item) => item.id !== listing.id && item.province === listing.province).slice(0, 4);
  return <><section className="listing-page shell"><header className="listing-heading"><div><p>{listing.locality}, {listing.province}</p><h1>{listing.title}</h1><div><span><Star fill="currentColor" />{listing.rating} · {listing.reviews} reviews</span><span><MapPin />{listing.localityType} of {listing.locality}</span></div></div><div className="listing-actions"><button><Share2 />Share</button><button className={saved ? 'saved' : ''} onClick={() => toggleFavorite(listing.id)}><Heart fill={saved ? 'currentColor' : 'none'} />{saved ? 'Saved' : 'Save'}</button></div></header><div className="listing-gallery"><img src={gallery[0]} alt={listing.title} /><img src={gallery[1]} alt={`${listing.title} interior`} /><img src={gallery[2]} alt={`${listing.title} detail`} /></div><div className="listing-content"><div className="listing-main"><section className="host-summary"><div><h2>Entire stay hosted by {listing.host}</h2><p>{listing.guests} guests · {listing.bedrooms} bedrooms · {listing.beds} beds · {listing.baths} baths</p></div><span>{listing.host.slice(0, 1)}</span></section><section className="stay-highlights"><div><UsersRound /><span><strong>Room for your group</strong><small>Comfortably hosts up to {listing.guests} guests.</small></span></div><div><Star /><span><strong>Loved by recent guests</strong><small>Rated {listing.rating} from {listing.reviews} stays.</small></span></div><div><MapPin /><span><strong>Great base for exploring</strong><small>Located in {listing.locality}, {listing.province}.</small></span></div></section><section className="listing-description"><p>{listing.description}</p></section><section className="sleeping"><h2>Where you’ll sleep</h2><div><article><BedDouble /><strong>Bedroom 1</strong><span>1 queen bed</span></article>{listing.bedrooms > 1 && <article><BedDouble /><strong>Bedroom 2</strong><span>{listing.beds > 2 ? '2 single beds' : '1 double bed'}</span></article>}<article><Bath /><strong>Baths</strong><span>{listing.baths} private bath{listing.baths > 1 ? 's' : ''}</span></article></div></section><section className="amenities-section"><h2>What this place offers</h2><div>{listing.amenities.map((amenity) => { const Icon = amenityIcons[amenity] || Star; return <span key={amenity}><Icon />{amenity}</span>; })}</div></section></div><BookingCard listing={listing} /></div><section className="listing-location"><h2>Where you’ll be</h2><p>{listing.locality}, {listing.province}, Philippines</p><MarketplaceMap listings={[listing]} /></section></section>{nearby.length > 0 && <section className="nearby-section"><div className="shell"><h2>More stays in {listing.province}</h2><ListingGrid listings={nearby} /></div></section>}</>;
}
