import { SlidersHorizontal, X } from 'lucide-react';
import { useState } from 'react';
import { amenities, locationHierarchy } from '../../data/marketplaceData';
import { useMarketplace } from '../../context/MarketplaceContext';

export function FilterPanel() {
  const [open, setOpen] = useState(false);
  const { filters, updateFilters, resetFilters } = useMarketplace();
  const localities = filters.province ? locationHierarchy.find((item) => item.province === filters.province)?.localities || [] : [];
  const toggleAmenity = (amenity) => updateFilters({ amenities: filters.amenities.includes(amenity) ? filters.amenities.filter((item) => item !== amenity) : [...filters.amenities, amenity] });
  const activeCount = Number(Boolean(filters.province)) + Number(Boolean(filters.locality)) + Number(filters.bedrooms > 0) + filters.amenities.length + Number(filters.instantBook) + Number(filters.maxPrice < 15000);
  return <><button className="filter-trigger" onClick={() => setOpen(true)}><SlidersHorizontal />Filters {activeCount > 0 && <span>{activeCount}</span>}</button>{open && <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && setOpen(false)}><section className="filter-modal" role="dialog" aria-modal="true" aria-label="Search filters"><header><h2>Filters</h2><button onClick={() => setOpen(false)} aria-label="Close filters"><X /></button></header><div className="filter-modal__body"><div className="filter-section"><h3>Location</h3><div className="two-fields"><label>Province<select value={filters.province} onChange={(event) => updateFilters({ province: event.target.value, locality: '' })}><option value="">All provinces</option>{locationHierarchy.map((item) => <option key={item.province}>{item.province}</option>)}</select></label><label>City / Municipality<select value={filters.locality} disabled={!filters.province} onChange={(event) => updateFilters({ locality: event.target.value })}><option value="">All localities</option>{localities.map((locality) => <option key={locality}>{locality}</option>)}</select></label></div></div><div className="filter-section"><h3>Price per night</h3><div className="price-range"><label>Minimum<input type="number" min="0" step="500" value={filters.minPrice} onChange={(event) => updateFilters({ minPrice: Number(event.target.value) })} /></label><span>—</span><label>Maximum<input type="number" min="1000" step="500" value={filters.maxPrice} onChange={(event) => updateFilters({ maxPrice: Number(event.target.value) })} /></label></div></div><div className="filter-section"><h3>Bedrooms</h3><div className="pill-options">{[0,1,2,3,4].map((number) => <button className={filters.bedrooms === number ? 'active' : ''} onClick={() => updateFilters({ bedrooms: number })} key={number}>{number === 0 ? 'Any' : `${number}+`}</button>)}</div></div><div className="filter-section"><h3>Amenities</h3><div className="amenity-options">{amenities.map((amenity) => <label key={amenity}><input type="checkbox" checked={filters.amenities.includes(amenity)} onChange={() => toggleAmenity(amenity)} /><span>{amenity}</span></label>)}</div></div><label className="switch-row"><span><strong>Instant Book</strong><small>Book without waiting for host approval</small></span><input type="checkbox" checked={filters.instantBook} onChange={(event) => updateFilters({ instantBook: event.target.checked })} /></label></div><footer><button className="clear-button" onClick={resetFilters}>Clear all</button><button className="primary-button" onClick={() => setOpen(false)}>Show stays</button></footer></section></div>}</>;
}
